[package]
name = "MoereumStdlib"
version = "1.0.0"
authors = []
dialect = "Moereum"

[addresses]
Std = "0x1"
PontemFramework = "0x1"
Root = "0xA550C18"

[dependencies]
MoveStdlib = { git = "https://github.com/NonceGeek/move-stdlib.git", rev = "release-v1.0.0"}
